# Generated by Django 5.1 on 2024-10-08 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_address', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.IntegerField()),
                ('item_regist_day', models.DateField()),
                ('item_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_app.usermodel')),
            ],
        ),
    ]
